version: "1"

services:
  api:
    container_name: Vesion
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    #remove for production
    volumes:
      - ./src:/usr/src

  mongodb_container:
    image: mongo:latest
    container_name: MongoDB
    ports:
      - 27017:27017
    restart:
      unless-stopped


