version: "3"

services:
  api:
    container_name: Vesion
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    #remove for production
    volumes:
      - ./src:/usr/src

  mongodb_container:
    image: mongo:latest
    container_name: MongoDB
    ports:
      - 27017:27017
    restart:
      unless-stopped

  influxdb_container:
    image: influxdb:latest
    container_name: InfluxDB
    ports:
      - 8086:8086
    environment: 
      - PORT=8086
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myusername
      - DOCKER_INFLUXDB_INIT_PASSWORD=passwordpasswordpassword
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10 
     
      


